services:
  - type: web
    name: flask-scraper
    env: python
    region: oregon
    buildCommand: |
      apt-get update
      apt-get install -y wget gnupg
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt-get install -y ./google-chrome-stable_current_amd64.deb
      apt-get install -y libx11-xcb1 libxcomposite1 libxdamage1 libxi6 libxtst6 libnss3 libxrandr2 libatk1.0-0 libcups2 libdrm2 libgbm1 libasound2 libpangocairo-1.0-0 libgtk-3-0
      wget https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
      unzip chromedriver_linux64.zip
      mv chromedriver /usr/bin/
      chmod +x /usr/bin/chromedriver
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_CHROME_BIN
        value: "/usr/bin/google-chrome-stable"
      - key: CHROMEDRIVER_PATH
        value: "/usr/bin/chromedriver"
