#!/usr/bin/env bash
# Exit on error
set -o errexit

# Define storage directory
STORAGE_DIR=/opt/render/project/.render

# Check if Chrome is already installed
if [[ ! -d $STORAGE_DIR/chrome ]]; then
  echo "...Downloading Chrome"
  mkdir -p $STORAGE_DIR/chrome
  cd $STORAGE_DIR/chrome
  wget -P ./ https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  apt-get install -y libglib2.0-0 libnss3 libgconf-2-4 libfontconfig1
  dpkg -x ./google-chrome-stable_current_amd64.deb $STORAGE_DIR/chrome
  rm ./google-chrome-stable_current_amd64.deb
  cd $HOME/project/src # Return to the project directory
else
  echo "...Using Chrome from cache"
fi

# Install Python dependencies
pip install --upgrade pip
pip install -r requirements.txt
